version: '3.8'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=news_board
      - POSTGRES_USER=news_board_user
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/DevelopsTodayTestAssignment
    ports:
      - "8000:8000"
    depends_on:
      - db